# 경로: .github/workflows/deploy.yml

name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PEM_KEY }}

          script: |
            # 1. nvm 환경 설정 불러오기
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. 프로젝트 폴더 경로 설정 및 생성/이동
            PROJECT_DIR="/home/ubuntu/SysInfo_V4"
            if [ ! -d "$PROJECT_DIR" ]; then
              git clone https://github.com/Hisabori/SysInfo_V4.git $PROJECT_DIR
            fi
            cd $PROJECT_DIR
            
            # 3. GitHub 최신 코드로 강제 덮어쓰기
            git fetch --all
            git reset --hard origin/main

            # 4. 프론트엔드 의존성 설치
            echo "--- Installing frontend dependencies ---"
            cd frontend
            npm install
            
            # 5. 백엔드 의존성 설치
            echo "--- Installing backend dependencies ---"
            cd ../backend
            npm install

            # 6. ★★★ 모든 설치가 끝난 후, 프로젝트 전체에 권한 부여! ★★★
            echo "--- Setting permissions ---"
            sudo chmod -R 755 $PROJECT_DIR
            
            # 7. 프론트엔드 빌드 (이제 권한 있음)
            echo "--- Building frontend ---"
            cd ../frontend
            npm run build

            # 8. 백엔드 재시작 (이제 권한 있음)
            echo "--- Restarting backend ---"
            cd ../backend
            npm run start

            # 9. Nginx 재시작
            echo "--- Restarting Nginx ---"
            sudo systemctl restart nginx