name: CI/CD Pipeline for SysInfo_V4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PEM_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 20m
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            if ! command -v yarn &> /dev/null
            then
                echo "--- Yarn not found, installing... ---"
                npm install -g yarn
            fi

            PROJECT_DIR="/var/www/SysInfo_V4"
            cd $PROJECT_DIR
            git fetch --all
            git reset --hard origin/main

            echo "--- Building Frontend ---"
            cd frontend
            yarn
            yarn build

            echo "--- Restarting Backend ---"
            cd ../backend
            yarn
            ./node_modules/.bin/pm2 restart sysinfo-backend || \
            ./node_modules/.bin/pm2 start server.js --name "sysinfo-backend"
            ./node_modules/.bin/pm2 save

            echo "--- Setting Permissions ---"
            sudo chmod -R 755 $PROJECT_DIR

            echo "--- Restarting Nginx ---"
            sudo systemctl restart nginx
