# 경로: .github/workflows/deploy.yml

name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PEM_KEY }}

          script: |
            # 1. nvm(Node Version Manager) 환경 설정 불러오기
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. 올바른 프로젝트 폴더로 이동
            cd /home/ubuntu/SysInfo_V4
            
            # 3. GitHub에서 최신 코드를 강제로 받아옴
            git fetch --all
            git reset --hard origin/main
            
            # 4. 프론트엔드 설치 및 빌드
            echo "--- Building Frontend ---"
            cd frontend
            npm install
            chmod +x node_modules/.bin/*
            npm run build

            # 5. 백엔드 설치 및 재시작
            echo "--- Restarting Backend ---"
            cd ../backend
            npm install
            chmod +x node_modules/.bin/* # <-- ★★ 여기! 백엔드용 권한 부여 ★★
            npm run start