# .github/workflows/deploy.yml

name: CI/CD Pipeline for SysInfo_V4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "=== Starting Deployment ==="

            # nvm 환경 설정
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # yarn 설치 여부 확인
            if ! command -v yarn &> /dev/null
            then
              echo "--- Yarn not found. Installing... ---"
              npm install -g yarn
            fi

            # 프로젝트 디렉토리 이동
            PROJECT_DIR="/var/www/SysInfo_V4"
            cd $PROJECT_DIR

            echo "--- Fetching latest code ---"
            git fetch --all
            git reset --hard origin/main

            # 프론트 빌드
            echo "--- Building Frontend ---"
            cd frontend
            yarn
            yarn build

            # 백엔드 빌드 및 PM2 재시작
            echo "--- Restarting Backend ---"
            cd ../backend
            yarn
            ./node_modules/.bin/pm2 restart sysinfo-backend || ./node_modules/.bin/pm2 start server.js --name "sysinfo-backend"
            ./node_modules/.bin/pm2 save

            # 권한 설정
            echo "--- Setting Permissions ---"
            sudo chmod -R 755 $PROJECT_DIR

            # Nginx 재시작
            echo "--- Restarting Nginx ---"
            sudo systemctl restart nginx

            echo "=== Deployment Finished ==="
          timeout: 30s
          command_timeout: 20m
          proxy_port: 22
          proxy_protocol: tcp
          proxy_timeout: 30s
          curl_insecure: false
          capture_stdout: false
