name: CI/CD Pipeline for SysInfo_V4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "=== Starting Deployment ==="

            # nvm 환경설정
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # yarn 설치 여부 확인
            if ! command -v yarn &> /dev/null
            then
              echo "--- Yarn not found. Installing... ---"
              npm install -g yarn
            fi

            # 프로젝트 디렉토리로 이동
            PROJECT_DIR="/var/www/SysInfo_V4"
            cd $PROJECT_DIR

            echo "--- Fetching latest code ---"
            git fetch --all
            git reset --hard origin/main

            echo "--- Building Frontend ---"
            cd frontend
            yarn
            yarn build

            echo "--- Restarting Backend ---"
            cd ../backend
            yarn
            ./node_modules/.bin/pm2 restart sysinfo-backend || ./node_modules/.bin/pm2 start server.js --name "sysinfo-backend"
            ./node_modules/.bin/pm2 save

            echo "--- Setting Permissions ---"
            sudo chmod -R 755 $PROJECT_DIR

            echo "--- Restarting Nginx ---"
            sudo systemctl restart nginx

            echo "=== Deployment Finished ==="
          timeout: 30s
          command_timeout: 20m
          # 필요 시 프록시 옵션은 아래처럼 지정 (없으면 빼도 됨)
          # proxy_host: ${{ secrets.PROXY_HOST }}
          # proxy_port: 22
          # proxy_username: ${{ secrets.PROXY_USERNAME }}
          # proxy_password: ${{ secrets.PROXY_PASSWORD }}
